### ISSUE TITLE
Repeated words 

### ISSUE THREAD

**Issue by Miniflowers** [eagerterrier/previous-wordle-words#1]
I used this site for months and have never had a problem. Suddenly, 2 days in a row, the days Wordle word was already listed. What is the problem? Please fix it! Thank you! :)

**Comment by eagerterrier** [comment]
hey @Miniflowers 

Sorry about this. I stopped playing the game, so was relying on wordle to allocate answers as it had done previously. Turns out they've changed and have a new editor in charge - https://www.mentalfloss.com/posts/wordle-editor-new-strategies - so the old way of doing it doesn't work.

Even with the old way, it's complicated, as there are some days when NYT ran one word early in the day only to withdraw it. I'm going to count these words as "used" so although we are on wordle 641 for my most recent data, there are 672 words in the pot!

I might change this strategy at some point, but I think it works for now.
